### ISSUE TITLE
Missing package dependencies

### ISSUE THREAD

**Issue by Schwenkner** [1iveowl/SocketLite#15]
I have formerly used version 4.0.6. Now after updating to 4.1.1 I have a compilation error at code like
var subscriberTcpListener = observerTcpListner.Subscribe
In the docs there are 3 parameters, 4.0.6 had only one there. After researching, where the 3 parameter signature comes from, it is an extension from Syste,.Reactive.Core. But these packages are not referenced as dependencies.

**Comment by 1iveowl** [comment]
What platform are you seeing this issue with? 

The only changes I did between 4.0.6 and 4.1.1 was to add support for .NET Standard 2.0. I didn't change the any signatures between those two release.

**Comment by 1iveowl** [comment]
Regarding System.Reactive. Looking at the NuGet System.Reactive 3.1.1 is a dependency for all platforms.

**Comment by 1iveowl** [comment]
How do I repo this?

**Comment by Schwenkner** [comment]
I hope I figured out the problem.
In the dependencies of Socketlite, there are only .Net Standard 1.5 and 2.0.
I use it with 1.4, for that no dependencies are defined, thus they are not inlcude. If you have a look into version 4.0.6, there are dependencies for the Reactive package also defined for .Net standard 1.0.

Can Socketlite 4.1.1 no more been used with .Net standard 1.4?

**Comment by 1iveowl** [comment]
I didn't change anything from 4.0.6 to 4.1.1 except add .NET Standard 2.0. 

Version 4.0.6 supported:
- NET 4.5.1
- Android
- iOS
- UWP
- .NET Standard 1.5

I don't recall why I made a dependency on .NET Standard 1.5.

Why do you need .NET Standard 1.4? I may go back and look at that option, but would be good to understand why it is necessary now that we have .NET Standard 2.0.

**Comment by Schwenkner** [comment]
I used 4.0.6 with .Net Standard 1.4 and it worked well. I think you can easily go back, even if nothing has been changed. How I understand the .Net standared version is always the minimal version needed. Thus if you enable it for 1.4 it is also possible to use with 2.0.

The need for using 1.4 for me comes from our customer. I use SocketLite in a tool which the customer uses on their software which only supports 1.4. So I cannot go to 1.6. But how you statet if nothing has been changed, then I can stay on 4.0.6 or include System.Reactive.Core manually.

**Comment by 1iveowl** [comment]
Thank you. I'm on the road traveling this week. Will look at it in the weekend.

It is still a mystery why 4.0.6 works for you and 4.1.1 does not. 

Is there any change that you could create a simple project to demonstrates this issue, so that I can reproduce and find a way around this for a future release?

**Comment by 1iveowl** [comment]
I created a new version 4.1.2-beta1 which includes support from .NET Standard 1.3.

Could you try and see if this fixes the issue?

**Comment by Schwenkner** [comment]
Thanks, I can only try this on Monday, will report you asap.

Gruß, Wernfried

Von: 1iveowl
Gesendet: Donnerstag, 19. Oktober 2017 00:08
An: 1iveowl/SocketLite
Cc: Schwenkner; Author
Betreff: Re: [1iveowl/SocketLite] Missing package dependencies (#15)

I created a new version 4.1.2-beta1 which includes support from .NET Standard 1.3.
Could you try and see if this fixes the issue?
